[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "autogradescope"
version = "0.1.0"
dependencies = ["pytest", "click", "rich"]

[project.scripts]
autogradescope = "autogradescope.__main__:main"
